/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const Root$schema = z.lazy(() => NominalNumber$schema(z.literal('Fixture')))
const NominalNumber$schema = (type0$schema) => z.intersection(z.number(), z.unknown())

export const Root = Root$schema

export const TYPERT = {
  package: '@fixture/schema',
  face: 'host',
  schemas: [
    { name: 'Root', schema: Root },
  ],
  invocations: [
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
